### DISCUSSION TITLE
Import Release from GitHub to PowerPlatform - Pre-Release?

### DISCUSSION THREAD

**Discussion by Asaurdiff-Tillamook** [microsoft/powerplatform-actions#279] [Q&A]
I am not sure if I am missing something, but your logic in the Import workflow should look for the "Pre-Release" selection in GutHub releases. If it is selected it should skip importing to the Production Environment. A pre-Release would be released back to Test/Dev for further testing, not released into the Prod Environment. 

Am I wrong?

**Comment by petrochuk** [comment]
which GitHub action are you talking about?

**Comment by Asaurdiff-Tillamook** [comment]
Hello @petrochuk, 

I had to remind myself about this. 
When i was working with the workflows you provided I noticed that they trigger off the publishing of the code. In GitHub you have the ability to state "Pre-Release". What I was thinking it that IF someone were to choose this they wouldn't want it to hit the specified "Production Environment" but to just move into the "testing environment" to Test the pre-release. 

Through a LOT of trial and error I was able to alter your workflows to trigger a different action sequence based on if the user wanted this to be a "Pre-Release" or if it goes straight to Production. If you want I can Post what i did?

**Reply by petrochuk** [reply]
Please share your changes

**Comment by Asaurdiff-Tillamook** [comment]
So looking over all of the src code in this repository I realize you are the source of the actual actions not the workflows i was presented. But This may still be useful for you. I basically removed the need to call the "microsoft/powerplatform-actions/import-solution@v0" and the exporting to Managed actions before this and stopped it based on the users selection of "Pre-Release" and "Release" instead of the "Created".

This is the original stated "Release Action call":
name: Release action
```
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]
```        
You will notice that it uses "created". Below is the small alterations i made on that. It became 2 calls instead of 1...
name: Release action
```
# Call the reusable workflow release-solution-to-prod-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [released]       
``` 
```
name: Release action
# Call the reusable workflow release-solution-to-Build-NonManaged.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [prereleased]  
```      
I was able to trigger off the different selections and the difference between the "release-solution-to-prod-with-inputs" and the "release-solution-to-Build-NonManaged" files is the the NonManaged file only utilize enough actions to bring the solution into Test Dev environment and the other is basically the original. 
Again, sorry since you are the source of the actions not the Workflows. I may have wrote this before fully understanding the workflow structure. But you still may find this process interesting since it allows users to differentiate between something going to Production versus Test.
