### ISSUE TITLE
`export-solution` - Error: Exporting to a target version is not supported in this release.

### ISSUE THREAD

**Issue by marktarry-mobysoft** [microsoft/powerplatform-actions#181]
We have the following action defined in a GitHub workflow:

```yaml
jobs:
  package-and-release:
    name: Package and Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      # Other steps

      - name: Export managed solution from build env
        uses: microsoft/powerplatform-actions/export-solution@0.5.2
        with:
          tenant-id: ${{ env.TENANT_ID }}
          environment-url: ${{ env.BUILD_ENVIRONMENT_URL }}
          app-id: ${{ env.BUILD_APP_ID }}
          client-secret: ${{ env.BUILD_APP_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-version: ${{ github.event.inputs.release_version }}
          managed: true
          solution-output-file: ${{ env.SHIPPING_FOLDER }}/${{ env.SOLUTION_NAME }}.zip
```

Each time this runs, we are encountering this error:
```
Starting Solution Export...

Microsoft PowerPlatform CLI

Version: 1.7.5+g64e6bc4

Error: Exporting to a target version is not supported in this release.
    Exporting to a target version is not supported in this release.
```

Note: if we omit `solution-version` then the action completes successfully, but the managed solution package no longer has the desired version.

We don't have a great deal of experience with the Power Platform stack (or Microsoft tech in general), so this could be a simple misunderstanding on our part, but it seems that the `solution-version` action input doesn't appear to work as documented.
