### ISSUE TITLE
[solution-import] add concrete error message when an environment variable is missing

### ISSUE THREAD

**Issue by henricson** [microsoft/powerplatform-actions#249]
Hi,

I had an issue where my unmanaged solution import failed with the very undescriptive message  "Error: The given key was not present in the dictionary.",.

After a lot of testing, I think I have isolated the error to be related to not having defined a deployment setting file, containing the required environment variable for my solution.

Here is my step-config, adding the last two lines resolved the error:

```
 - name: Import solution as unmanaged to build env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{inputs.BUILD_ENVIRONMENT_URL}}
          app-id: ${{inputs.CLIENT_ID}}
          client-secret: ${{ secrets.envSecret }}
          tenant-id: ${{inputs.TENANT_ID}}
          solution-file: ${{ inputs.solution_outbound_folder}}/${{ inputs.solution_name }}.zip
          force-overwrite: true
          publish-changes: true
          run-asynchronously: true
          use-deployment-settings-file: true
          deployment-settings-file: "env.json"
```

It took me some time to isolate this error, and I think it would be great to include a more descriptive error message.

It seems like this error message is raised over http from the target environment itself, so I guess a possible fix would to be to add some client-side validations on the solution-import action, checking the contents environmentvariabledefinition.xml. Might add my first open source pull-request, if someone can confirm that my thinking is right here :)
