### ISSUE TITLE
Sometimes import-solution disables flows and workflows

### ISSUE THREAD

**Issue by BrainSlugs83** [microsoft/powerplatform-actions#283]
It seems that randomly, after deployment of a solution (via import-solution), flows and workflows (aka Power Automate Flows, and Processes) are disabled after deployment. -- Even if that particular flow was not impacted by the solution changes.

There does not seem to be any rhyme or reason or way to predict when it happens or why.

Can you please include an argument to turn back on all flows and workflows after deployment?

Here is an example:
```
uses: microsoft/powerplatform-actions/import-solution@v0
with:
  environment-url: '${{ inputs.target_environment }}'
  user-name: ${{ secrets.POWERAPPS_USER }}
  password-secret: ${{ secrets.POWERAPPS_PWD }}
  solution-file: 'My-Flows-Solution.zip'
  activate-plugins: true
  force-overwrite: true
  publish-changes: true
  working-directory: 'root\PowerApps\Solutions\'
  run-asynchronously: true
  convert-to-managed: '${{ inputs.managed }}'
```

I have seen both Power Automate Flows, and Workflows (Processes) get disabled, completely randomly, as a result of the deployment. -- Usually just manually turning them back on fixes things... but the whole point of what we're trying to do is to *automate* deployment.
