### ISSUE TITLE
V1 action for export solution fails on @latest tag.

### ISSUE THREAD

**Issue by michaelgevaryahu** [microsoft/powerplatform-actions#444]
@latest tag export action fails. Action puts /latest/ into the file path (instead of the targeted version) and fails to find PAC installed, when v1 should be used in the file path.

**Comment by michaelgevaryahu** [comment]
same defect in import action.

**Comment by tehcrashxor** [comment]
> Action puts /latest/ into the file path (instead of the targeted version)

If you specified `@latest`, then `latest` is the targeted version.  I don't understand what point you're trying to make there?

As for the export action, it's working for me when I target `@latest`:

```yaml
jobs:
  v1-actions-install-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false  # if either Windows or Ubuntu fail, continue executing the other env
    steps:
      - name: Install 
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: WhoAmI
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
          solution-name: emptySolution
          solution-output-file: 'example.zip'
```
which runs succesfully:
![image](https://github.com/microsoft/powerplatform-actions/assets/3751389/2b068750-fd64-4894-9099-52b408147eb3)

Do you have any more information on how it's failing for you?
