### ISSUE TITLE
New action request for copilot publish

### ISSUE THREAD

**Issue by prabdeb** [microsoft/powerplatform-actions#620]
Requesting for new action that will publish Copilot after solution import.

Reference command: [pac copilot publish](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/copilot#pac-copilot-publish)

**Comment by devkeydet** [comment]
I will defer to the GitHub Actions for Power Platform team on the feature request, but have a workaround to unblock you for now.  GitHub Actions for Power Platform have an "escape hatch" when the actions haven't caught up to the underlying `pac` commands.  When you use `actions-install`, set `add-tools-to-path: true`.   By doing so, you get the version of `pac` that the actions use.  You can then use it directly in script actions.  Here's an example:

``` yaml
name: use-pac-from-actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Install Power Platform Actions
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          add-tools-to-path: true
      - name: create pac auth profile
        shell: pwsh
        run: |
          # create a pac auth profile
          pac auth create --name temp-for-workflow --url ${{ secrets.ENVIRONMENT_URL }} --applicationId ${{ secrets.APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      - name: use pac
        shell: pwsh
        run: |
          # use pac with the profile created
          pac auth who
```
