### ISSUE TITLE
Async import-solution action times out after 1 hour but solution gets imported anyway

### ISSUE THREAD

**Issue by nkirstein** [microsoft/powerplatform-actions#86]
I'm using the `pack-solution` and `import-solution` actions to import an unmanaged solution from a GH repo to a dev environment. This is how I use the `import-solution` action:

```
- name: Import unmanaged solution to dev
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ env.DEV_URL }}
        app-id: ${{ env.APP_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-file: out/solutions/${{ env.SOLUTION }}.zip
        run-asynchronously: true
        force-overwrite: true
        publish-changes: true
```
Most of the time this works as expected, but sometimes the action runs for an hour and then times out with `Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'.` But when I check the target environment, the solution has actually been imported and works just fine. 

I've experienced this with different solutions and different environments. It's also happened with small solutions that usually only take a few minutes to import. Any ideas why this might be happening? It's a bit frustrating because every time this happens a full 60 minutes of run time get added to your billable GH actions minutes.
